---
- name: "Check if nginx-exporter binary exist"
  stat:
    path: "/usr/local/bin/nginx-prometheus-exporter"
  register: nginx_exporter_binary

- when: not nginx_exporter_binary.stat.exists or nginx_exporter_upgrade
  block:
    - name: "Download nginx-exporter..."
      get_url:
        url: '{{ nginx_exporter_url }}'
        dest: /tmp/
        timeout: 60

    - name: "Extract archive"
      unarchive:
        src: "/tmp/{{ nginx_exporter_tgz }}"
        dest: "/usr/local/bin/"
        mode: 0755
        remote_src: true

- name: "Create systemd for nginx_exporter"
  template:
    src: nginx_exporter.service.j2
    dest: /etc/systemd/system/nginx_exporter.service
    mode: 0644
  notify: "restart nginx_exporter"

- name: "Start nginx_exporter.service"
  systemd:
    name: nginx_exporter
    state: started
    enabled: true
    daemon_reload: true
